#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01). Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.

dns_resolv () {
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
	dns_resolv "$1" "www"
	dns_resolv "$1" "lb-01"
	dns_resolv "$1" "web-01"
	dns_resolv "$1" "web-02"
elif [ "$#" == 2 ]
then
	dns_resolv "$1" "$2"
fi
