#!/usr/bin/env bash
#Web servers are the piece of software generating and serving HTML pages, let’s install one!

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
chown -R $USER:$USER /var/html

echo 'Hello World!' > /var/www/html/index.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-avaible/default

service nginx start
