#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.


apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
chown -R $USER:$USER /var/www/html

echo 'Hello World!' > /var/www/html/index.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location = /redirect_me/ {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
