#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.


apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
chown -R "$USER":"$USER" /var/www/html

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/no_found.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	error_page 404 /no_found.html;
	location = /xyz {
		root /var/www/html;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
