#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#installation
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*

#configuration
printf "%s" "frontend http_front
   bind *:80
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 3.86.13.76:80 check
   server web-02 54.90.47.244:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy start
