#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.


i=1
while (( i>0 ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
	i=$(( i+1 ))
done
