#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and:
#    displays 4 and then bad luck from China for the 4th loop iteration
#    displays 9 and then bad luck from Japan for the 9th loop iteration
#    displays 17 and then bad luck from Italy for the 17th loop iteration



i=1
while (( i<101 ))
do
	if (( i % 3  == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$(( i+1 ))
done
