#!/usr/bin/env bash
#Bash script that displays:
#    The content of the current directory
#    In a list format
#    Where only the part of the name after the first dash is displayed


list=$( find ./ -type f | cut -d '-' -f2)
for i in $list
do
	echo "$i"
done
