#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01

apt update && apt-get -y install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 443
ufw allow 80
ufw enable
