#!/usr/bin/env bash
#Firewalls can not only filter requests, they can also forward them.


apt update && apt-get -y install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 443
ufw allow 80

echo "*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT" >> /etc/ufw/before.rules

ufw restart
