#!/usr/bin/env bash
#it is preferable to run as a privileged user, meaning that the user also has the ability to perform tasks that the root user can do, just need to use a specific command that you need to discover

echo "$1"
sudo gpasswd -a "$1" sudo
