#!/usr/bin/env bash
#Fix container so that Nginx is running as the nginx user.
sudo su
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
